name: Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    defaults:
      run:
        working-directory: ./back-end-app
    runs-on: ubuntu-latest
    permissions: # Añadimos permisos para que la acción pueda leer y escribir en el registry de Github
      packages: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Manage NPM Dependencies
        uses: ./.github/actions/cache-node-dependencies
        with:
          # Pasamos otros valores, en este caso para el backend
          app-name: "nest-app"
          working-directory: "./back-end-app"

      - name: Build
        run: npm run build
      
      - name: Lint
        run: npm run lint 
      - name: Test
        run: npm run test

      - name: SonarCloud
        uses: SonarSource/sonarqube-scan-action@v6
        with: # Muy importante esta parte, ya que le dice a SonarCloud que sólo analice el proyecto de back
          projectBaseDir: back-end-app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACK }}
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3 # Utilizamos la acción de login de Docker del marketplace
        with:
          registry: ghcr.io # añadimos Github como registry de docker
          username: ${{ github.actor }} # El usuario de Github
          password: ${{ secrets.GITHUB_TOKEN }} # El token de Github que ya viene por defecto en los secrets
      
      - name: handle repo naming
        id: docker-metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.actor }}/pipelinecicd_back

      - name: Build Docker Image
        uses: docker/build-push-action@v5 # Utilizamos la acción de build y push de docker del marketplace. Esto hace el docker build y el docker push por debajo
        with:
          context: ./back-end-app # El working directory
          push: true
          tags: ${{ steps.docker-metadata.outputs.tags }}
          labels: ${{ steps.docker-metadata.outputs.labels }}